services:
  postgres:
    image: postgis/postgis:15
    environment:
      POSTGRES_DB: landmarks
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: